import pyxel

KEY_LIST = [
    pyxel.KEY_SPACE,
    # pyxel.KEY_QUOTE,
    pyxel.KEY_COMMA,
    pyxel.KEY_MINUS,
    pyxel.KEY_PERIOD,
    pyxel.KEY_SLASH,
    pyxel.KEY_0,
    pyxel.KEY_1,
    pyxel.KEY_2,
    pyxel.KEY_3,
    pyxel.KEY_4,
    pyxel.KEY_5,
    pyxel.KEY_6,
    pyxel.KEY_7,
    pyxel.KEY_8,
    pyxel.KEY_9,
    pyxel.KEY_SEMICOLON,
    pyxel.KEY_EQUAL,
    pyxel.KEY_A,
    pyxel.KEY_B,
    pyxel.KEY_C,
    pyxel.KEY_D,
    pyxel.KEY_E,
    pyxel.KEY_F,
    pyxel.KEY_G,
    pyxel.KEY_H,
    pyxel.KEY_I,
    pyxel.KEY_J,
    pyxel.KEY_K,
    pyxel.KEY_L,
    pyxel.KEY_M,
    pyxel.KEY_N,
    pyxel.KEY_O,
    pyxel.KEY_P,
    pyxel.KEY_Q,
    pyxel.KEY_R,
    pyxel.KEY_S,
    pyxel.KEY_T,
    pyxel.KEY_U,
    pyxel.KEY_V,
    pyxel.KEY_W,
    pyxel.KEY_X,
    pyxel.KEY_Y,
    pyxel.KEY_Z,
    pyxel.KEY_LEFT_BRACKET,
    pyxel.KEY_BACKSLASH,
    pyxel.KEY_RIGHT_BRACKET,
    # pyxel.KEY_BACKQUOTE,
    pyxel.KEY_ESCAPE,
    pyxel.KEY_ENTER,
    pyxel.KEY_TAB,
    pyxel.KEY_BACKSPACE,
    pyxel.KEY_INSERT,
    pyxel.KEY_DELETE,
    pyxel.KEY_RIGHT,
    pyxel.KEY_LEFT,
    pyxel.KEY_DOWN,
    pyxel.KEY_UP,
    pyxel.KEY_PAGE_UP,
    pyxel.KEY_PAGE_DOWN,
    pyxel.KEY_HOME,
    pyxel.KEY_END,
    pyxel.KEY_CAPS_LOCK,
    pyxel.KEY_SCROLL_LOCK,
    pyxel.KEY_NUM_LOCK,
    pyxel.KEY_PRINT_SCREEN,
    pyxel.KEY_PAUSE,
    pyxel.KEY_F1,
    pyxel.KEY_F2,
    pyxel.KEY_F3,
    pyxel.KEY_F4,
    pyxel.KEY_F5,
    pyxel.KEY_F6,
    pyxel.KEY_F7,
    pyxel.KEY_F8,
    pyxel.KEY_F9,
    pyxel.KEY_F10,
    pyxel.KEY_F11,
    pyxel.KEY_F12,
    pyxel.KEY_KP_0,
    pyxel.KEY_KP_1,
    pyxel.KEY_KP_2,
    pyxel.KEY_KP_3,
    pyxel.KEY_KP_4,
    pyxel.KEY_KP_5,
    pyxel.KEY_KP_6,
    pyxel.KEY_KP_7,
    pyxel.KEY_KP_8,
    pyxel.KEY_KP_9,
    pyxel.KEY_KP_DECIMAL,
    pyxel.KEY_KP_DIVIDE,
    pyxel.KEY_KP_MULTIPLY,
    pyxel.KEY_KP_SUBTRACT,
    pyxel.KEY_KP_ADD,
    pyxel.KEY_KP_ENTER,
    pyxel.KEY_KP_EQUAL,
    pyxel.KEY_LEFT_SHIFT,
    pyxel.KEY_LEFT_CONTROL,
    pyxel.KEY_LEFT_ALT,
    pyxel.KEY_LEFT_SUPER,
    pyxel.KEY_RIGHT_SHIFT,
    pyxel.KEY_RIGHT_CONTROL,
    pyxel.KEY_RIGHT_ALT,
    pyxel.KEY_RIGHT_SUPER,
    pyxel.KEY_MENU,
    pyxel.KEY_SHIFT,
    pyxel.KEY_CONTROL,
    pyxel.KEY_ALT,
    pyxel.KEY_SUPER,
    pyxel.MOUSE_LEFT_BUTTON,
    pyxel.MOUSE_MIDDLE_BUTTON,
    pyxel.MOUSE_RIGHT_BUTTON,
    pyxel.GAMEPAD_1_A,
    pyxel.GAMEPAD_1_B,
    pyxel.GAMEPAD_1_X,
    pyxel.GAMEPAD_1_Y,
    pyxel.GAMEPAD_1_LEFT_SHOULDER,
    pyxel.GAMEPAD_1_RIGHT_SHOULDER,
    pyxel.GAMEPAD_1_SELECT,
    pyxel.GAMEPAD_1_START,
    pyxel.GAMEPAD_1_UP,
    pyxel.GAMEPAD_1_RIGHT,
    pyxel.GAMEPAD_1_DOWN,
    pyxel.GAMEPAD_1_LEFT,
    pyxel.GAMEPAD_2_A,
    pyxel.GAMEPAD_2_B,
    pyxel.GAMEPAD_2_X,
    pyxel.GAMEPAD_2_Y,
    pyxel.GAMEPAD_2_LEFT_SHOULDER,
    pyxel.GAMEPAD_2_RIGHT_SHOULDER,
    pyxel.GAMEPAD_2_SELECT,
    pyxel.GAMEPAD_2_START,
    pyxel.GAMEPAD_2_UP,
    pyxel.GAMEPAD_2_RIGHT,
    pyxel.GAMEPAD_2_DOWN,
    pyxel.GAMEPAD_2_LEFT,
]

KEY_DICT = {
    pyxel.KEY_SPACE: "SPACE",
    # pyxel.KEY_QUOTE: "QUOTE",
    pyxel.KEY_COMMA: "COMMA",
    pyxel.KEY_MINUS: "MINUS",
    pyxel.KEY_PERIOD: "PERIOD",
    pyxel.KEY_SLASH: "SLASH",
    pyxel.KEY_0: "0",
    pyxel.KEY_1: "1",
    pyxel.KEY_2: "2",
    pyxel.KEY_3: "3",
    pyxel.KEY_4: "4",
    pyxel.KEY_5: "5",
    pyxel.KEY_6: "6",
    pyxel.KEY_7: "7",
    pyxel.KEY_8: "8",
    pyxel.KEY_9: "9",
    pyxel.KEY_SEMICOLON: "SEMICOLON",
    pyxel.KEY_EQUAL: "EQUAL",
    pyxel.KEY_A: "A",
    pyxel.KEY_B: "B",
    pyxel.KEY_C: "C",
    pyxel.KEY_D: "D",
    pyxel.KEY_E: "E",
    pyxel.KEY_F: "F",
    pyxel.KEY_G: "G",
    pyxel.KEY_H: "H",
    pyxel.KEY_I: "I",
    pyxel.KEY_J: "J",
    pyxel.KEY_K: "K",
    pyxel.KEY_L: "L",
    pyxel.KEY_M: "M",
    pyxel.KEY_N: "N",
    pyxel.KEY_O: "O",
    pyxel.KEY_P: "P",
    pyxel.KEY_Q: "Q",
    pyxel.KEY_R: "R",
    pyxel.KEY_S: "S",
    pyxel.KEY_T: "T",
    pyxel.KEY_U: "U",
    pyxel.KEY_V: "V",
    pyxel.KEY_W: "W",
    pyxel.KEY_X: "X",
    pyxel.KEY_Y: "Y",
    pyxel.KEY_Z: "Z",
    pyxel.KEY_LEFT_BRACKET: "LEFT_BRACKET",
    pyxel.KEY_BACKSLASH: "BACKSLASH",
    pyxel.KEY_RIGHT_BRACKET: "RIGHT_BRACKET",
    # pyxel.KEY_BACKQUOTE: "BACKQUOTE",
    pyxel.KEY_ESCAPE: "ESCAPE",
    pyxel.KEY_ENTER: "ENTER",
    pyxel.KEY_TAB: "TAB",
    pyxel.KEY_BACKSPACE: "BACKSPACE",
    pyxel.KEY_INSERT: "INSERT",
    pyxel.KEY_DELETE: "DELETE",
    pyxel.KEY_RIGHT: "RIGHT",
    pyxel.KEY_LEFT: "LEFT",
    pyxel.KEY_DOWN: "DOWN",
    pyxel.KEY_UP: "UP",
    pyxel.KEY_PAGE_UP: "PAGE_UP",
    pyxel.KEY_PAGE_DOWN: "PAGE_DOWN",
    pyxel.KEY_HOME: "HOME",
    pyxel.KEY_END: "END",
    pyxel.KEY_CAPS_LOCK: "CAPS_LOCK",
    pyxel.KEY_SCROLL_LOCK: "SCROLL_LOCK",
    pyxel.KEY_NUM_LOCK: "NUM_LOCK",
    pyxel.KEY_PRINT_SCREEN: "PRINT_SCREEN",
    pyxel.KEY_PAUSE: "PAUSE",
    pyxel.KEY_F1: "F1",
    pyxel.KEY_F2: "F2",
    pyxel.KEY_F3: "F3",
    pyxel.KEY_F4: "F4",
    pyxel.KEY_F5: "F5",
    pyxel.KEY_F6: "F6",
    pyxel.KEY_F7: "F7",
    pyxel.KEY_F8: "F8",
    pyxel.KEY_F9: "F9",
    pyxel.KEY_F10: "F10",
    pyxel.KEY_F11: "F11",
    pyxel.KEY_F12: "F12",
    pyxel.KEY_KP_0: "KP_0",
    pyxel.KEY_KP_1: "KP_1",
    pyxel.KEY_KP_2: "KP_2",
    pyxel.KEY_KP_3: "KP_3",
    pyxel.KEY_KP_4: "KP_4",
    pyxel.KEY_KP_5: "KP_5",
    pyxel.KEY_KP_6: "KP_6",
    pyxel.KEY_KP_7: "KP_7",
    pyxel.KEY_KP_8: "KP_8",
    pyxel.KEY_KP_9: "KP_9",
    pyxel.KEY_KP_DECIMAL: "KP_DECIMAL",
    pyxel.KEY_KP_DIVIDE: "KP_DIVIDE",
    pyxel.KEY_KP_MULTIPLY: "KP_MULTIPLY",
    pyxel.KEY_KP_SUBTRACT: "KP_SUBTRACT",
    pyxel.KEY_KP_ADD: "KP_ADD",
    pyxel.KEY_KP_ENTER: "KP_ENTER",
    pyxel.KEY_KP_EQUAL: "KP_EQUAL",
    pyxel.KEY_LEFT_SHIFT: "LEFT_SHIFT",
    pyxel.KEY_LEFT_CONTROL: "LEFT_CONTROL",
    pyxel.KEY_LEFT_ALT: "LEFT_ALT",
    pyxel.KEY_LEFT_SUPER: "LEFT_SUPER",
    pyxel.KEY_RIGHT_SHIFT: "RIGHT_SHIFT",
    pyxel.KEY_RIGHT_CONTROL: "RIGHT_CONTROL",
    pyxel.KEY_RIGHT_ALT: "RIGHT_ALT",
    pyxel.KEY_RIGHT_SUPER: "RIGHT_SUPER",
    pyxel.KEY_MENU: "MENU",
    pyxel.KEY_SHIFT: "SHIFT",
    pyxel.KEY_CONTROL: "CONTROL",
    pyxel.KEY_ALT: "ALT",
    pyxel.KEY_SUPER: "SUPER",
    pyxel.MOUSE_LEFT_BUTTON: "MOUSE_LEFT_BUTTON",
    pyxel.MOUSE_MIDDLE_BUTTON: "MOUSE_MIDDLE_BUTTON",
    pyxel.MOUSE_RIGHT_BUTTON: "MOUSE_RIGHT_BUTTON",
    pyxel.GAMEPAD_1_A: "GAMEPAD_1_A",
    pyxel.GAMEPAD_1_B: "GAMEPAD_1_B",
    pyxel.GAMEPAD_1_X: "GAMEPAD_1_X",
    pyxel.GAMEPAD_1_Y: "GAMEPAD_1_Y",
    pyxel.GAMEPAD_1_LEFT_SHOULDER: "GAMEPAD_1_LEFT_SHOULDER",
    pyxel.GAMEPAD_1_RIGHT_SHOULDER: "GAMEPAD_1_RIGHT_SHOULDER",
    pyxel.GAMEPAD_1_SELECT: "GAMEPAD_1_SELECT",
    pyxel.GAMEPAD_1_START: "GAMEPAD_1_START",
    pyxel.GAMEPAD_1_UP: "GAMEPAD_1_UP",
    pyxel.GAMEPAD_1_RIGHT: "GAMEPAD_1_RIGHT",
    pyxel.GAMEPAD_1_DOWN: "GAMEPAD_1_DOWN",
    pyxel.GAMEPAD_1_LEFT: "GAMEPAD_1_LEFT",
    pyxel.GAMEPAD_2_A: "GAMEPAD_2_A",
    pyxel.GAMEPAD_2_B: "GAMEPAD_2_B",
    pyxel.GAMEPAD_2_X: "GAMEPAD_2_X",
    pyxel.GAMEPAD_2_Y: "GAMEPAD_2_Y",
    pyxel.GAMEPAD_2_LEFT_SHOULDER: "GAMEPAD_2_LEFT_SHOULDER",
    pyxel.GAMEPAD_2_RIGHT_SHOULDER: "GAMEPAD_2_RIGHT_SHOULDER",
    pyxel.GAMEPAD_2_SELECT: "GAMEPAD_2_SELECT",
    pyxel.GAMEPAD_2_START: "GAMEPAD_2_START",
    pyxel.GAMEPAD_2_UP: "GAMEPAD_2_UP",
    pyxel.GAMEPAD_2_RIGHT: "GAMEPAD_2_RIGHT",
    pyxel.GAMEPAD_2_DOWN: "GAMEPAD_2_DOWN",
    pyxel.GAMEPAD_2_LEFT: "GAMEPAD_2_LEFT",
}